name: Hello GitHub Actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Say hello
        run: echo "GitHub Actions is running"

      - name: Show files
        run: ls
